/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_4x1
(
    input [1:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    output reg out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


// Register for storing large constants.
// There is a 1-bit command describing this register. 
// In this way, 15 bits can be stored (the 16th bit 
// activates the writing of this register and therefore 
// is always one). The 16th bit will be set according 
// to the 'immediate extend mode' (iem).
module ImReg (
  input en, // enables storage
  input [1:0] iem, // immediate extend mode (0: sign extend; 1: extend with 0, 2:extend with S0, 3:extend with D0)
  input C,
  input [15:0] inst, // the current instruction
  output [15:0] imm // The constant of register contents and bit 8.

);
  wire [14:0] s0;
  wire [14:0] s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  assign s2 = inst[0];
  assign s3 = inst[4];
  assign s0 = inst[14:0];
  // imm
  DIG_Register_BUS #(
    .Bits(15)
  )
  DIG_Register_BUS_i0 (
    .D( s0 ),
    .C( C ),
    .en( en ),
    .Q( s1 )
  );
  assign s5 = s1[14];
  Mux_4x1 Mux_4x1_i1 (
    .sel( iem ),
    .in_0( s5 ),
    .in_1( 1'b0 ),
    .in_2( s2 ),
    .in_3( s3 ),
    .out( s4 )
  );
  assign imm[14:0] = s1;
  assign imm[15] = s4;
endmodule
module Register1
  (
    input D,
    input C,
    input en,
    input rst_n,
    output Q
  );

  reg  state;

  assign Q = state;

  always @ (negedge C, negedge rst_n)
  begin

    if(!rst_n)
    begin
      state <= 1'h0;
    end
    else
      if (en)
        state <= D;

  end
endmodule


module register_1bit (
  input D,
  input C,
  input en,
  input rst,
  output Q
);
  // Register1
  Register1 Register1_i0 (
    .D( D ),
    .C( C ),
    .en( en ),
    .rst_n( rst ),
    .Q( Q )
  );
endmodule
module Register8
  (
    input [7:0]D,
    input C,
    input en,
    input rst_n,
    output [7:0]Q
  );

  reg [7:0] state ;

  assign Q = state;

  always @ (posedge C or negedge rst_n)
  begin
    if(!rst_n)
    begin
      state <= 8'h0;
    end
    else
      if (en)
        state <= D;


  end
endmodule


module register_8bit (
  input [7:0] D,
  input C,
  input en,
  input rst,
  output [7:0] Q
);
  // Register8
  Register8 Register8_i0 (
    .D( D ),
    .C( C ),
    .en( en ),
    .rst_n( rst ),
    .Q( Q )
  );
endmodule
module programCounter
  (
    input  wire [15:0] AluIn,
    input  wire        clk,
    input  wire        rst_n,
    input  wire        pc_en,
    input  wire        absJmp,
    input  wire        intr,
    input  wire        reti,
    input  wire        relJmp,
    output wire [15:0] PC
  );

  localparam [15:0] interuptFuncAdr = 16'h0002;
  reg [15:0] interruptAdress;

  reg [15:0] PCr;

  assign PC     = PCr;

  always @(posedge clk , negedge rst_n)
  begin
    if (!rst_n)
    begin
      PCr     <= 16'h0000;
      interruptAdress <= 16'h0000;
    end
    else if (pc_en)
    begin
      if (reti)
      begin
        PCr     <= interruptAdress + 16'd1;
      end
      else if (intr)
      begin
        if (relJmp || absJmp)
          interruptAdress <= PCr - 16'd1;
        else
          interruptAdress <= PCr;

        PCr     <= interuptFuncAdr;
      end
      else if (relJmp)
      begin
        PCr     <= PCr + AluIn + 16'd1;
      end
      else if (absJmp)
      begin
        PCr     <= AluIn;
      end
      else
      begin
        PCr     <= PCr + 16'd1;
      end
    end
  end

endmodule

module spi_memory_interface (
    input  wire        clk,           // System clock
    input  wire        spi_rst_n,       // Reset
    input  wire        st,            // Store (write) signal
    input  wire        ld,            // Load (read) signal
    input  wire [15:0] addr,          // 16-bit memory address
    input  wire [15:0] data_in,       // 16-bit data input (for write)
    output reg  [15:0] data_out,      // 16-bit data output (for read)
    output reg         spi_cs,        // SPI Chip Select (Active Low)
    output reg         spi_clk,       // SPI Clock
    output reg         busy,          // Busy signal
    output reg         spi_mosi,      // SPI MOSI (Master Out Slave In)
    input  wire        spi_miso      // SPI MISO (Master In Slave Out)

  );

  // Define FSM states

  localparam  IDLE = 4'b0000;
  localparam  START = 4'b0001;
  localparam  SEND_CMD = 4'b0010;
  localparam  SEND_ADDR = 4'b0011;
  localparam  WRITE_DATA = 4'b0100;
  localparam  READ_DATA = 4'b0101;
  localparam  STOP = 4'b0110;
  localparam  TOGGLECLKON = 4'b0111;
  localparam  decideFate = 4'b1000;

  localparam  STcom = 1;
  localparam  LDcom = 0;


  reg[4:0] state;
  reg[4:0] last_state;
  reg command;

  reg [7:0] shift_reg; // Shift register for SPI data
  reg [5:0] bit_cnt;   // Bit counter
  reg [2:0] byte_cnt;  // Byte counter
  reg [15:0] recv_data;// Temporary storage for received data

  reg [0:0] prev_command;
  reg [15:0] prev_addr;
  wire [23:0] spi_addr;
  assign spi_addr = {7'b0000000, addr, 1'b0};

  always @(posedge clk , negedge spi_rst_n)
  begin

    if (!spi_rst_n)
    begin
      state   <= IDLE;
      spi_cs  <= 1'b1;
      spi_clk <= 1'b0;
      spi_mosi <= 1'b0;
      busy    <= 1'b0;
      bit_cnt <= 3'b000;
      byte_cnt <= 3'b000;
      command <= STcom;
      state <= IDLE;
      last_state <= IDLE;
    end
    else
    begin
      case (state)
        IDLE:
        begin
          busy <= 1'b0;
          if (st || ld)
          begin
            state <= START;
            busy <= 1'b1;

            prev_command <= command;
            prev_addr <= addr;

            if (st)
            begin
              shift_reg <= 8'h02; // Write command
              command <= STcom;
            end

            else if (ld)
            begin
              shift_reg <= 8'h03; // Read command
              command <= LDcom;
            end

          end
        end

        START:
        begin
          spi_cs <=1'b0;
          bit_cnt <= 3'b000;
          byte_cnt <= 3'b000;
          state <= SEND_CMD;
        end

        SEND_CMD:
        begin
          spi_clk <= 0;
          if (bit_cnt < 8)
          begin
            spi_mosi <= shift_reg[7];   // Send MSB first
            shift_reg <= shift_reg << 1;
            last_state <= state;
            state <= TOGGLECLKON;
            bit_cnt <= bit_cnt + 1;
          end
          else
          begin
            state <= SEND_ADDR;
            shift_reg <= spi_addr[23:16] ;         // top address byte for 24-bit SPI flash
            bit_cnt <= 0;
            byte_cnt <= 0;
          end
        end

        SEND_ADDR:
        begin
          spi_clk <= 0;

          if (bit_cnt < 8)
          begin
            spi_mosi <= shift_reg[7];
            shift_reg <= shift_reg << 1;
            last_state <= state;
            state <= TOGGLECLKON;
            bit_cnt <= bit_cnt + 1;
          end
          else if (byte_cnt == 0)
          begin
            shift_reg <= spi_addr[15:8];    // middle address byte
            byte_cnt <= 1;
            bit_cnt <= 0;
          end
          else if (byte_cnt == 1)
          begin
            shift_reg <= spi_addr[7:0];     // low address byte
            byte_cnt <= 2;
            bit_cnt <= 0;
          end
          else
          begin
            state <= command ? WRITE_DATA : READ_DATA;
            shift_reg <= command ? data_in[15:8] : 8'h00;
            recv_data <= 16'h0000;
            bit_cnt <= 0;
            byte_cnt <= 0;
            spi_mosi <= 1'b0;
          end
        end

        WRITE_DATA:
        begin

          spi_clk <= 0;
          if (bit_cnt < 8)
          begin
            spi_mosi <= shift_reg[7];
            shift_reg <= shift_reg << 1;

            last_state <= state;
            state <= TOGGLECLKON;
            bit_cnt <= bit_cnt + 1;
          end
          else if (byte_cnt == 0)
          begin
            shift_reg <= data_in[7:0]; // Load low byte
            byte_cnt <= 1;
            bit_cnt <= 0;
          end
          else
          begin
            state <= decideFate; // Decide next state based on command
          end
        end

        READ_DATA:
        begin

          spi_clk <= 0;
          if (bit_cnt < 17)
          begin
            last_state<=state;

            if (bit_cnt<16)
              state <= TOGGLECLKON;
            bit_cnt <= bit_cnt + 1;
            recv_data[15:0] <= {recv_data[14:0], spi_miso}; // Shift left


          end
          else
          begin
            recv_data[15:0] <= {recv_data[14:0], spi_miso};
            data_out <= recv_data;
            state <= decideFate; // Decide next state based on command
            bit_cnt <= 0;
          end
        end


        STOP:
        begin

          spi_clk <= 0;
          spi_cs <= 1'b1;
          busy <= 1'b0;
          state <= IDLE;
        end

        TOGGLECLKON:
        begin
          spi_clk <= 1;
          state <= last_state;
        end

        decideFate:
        begin
          if (command == prev_command &&
              addr == prev_addr + 1 )
          begin
            // Continue without releasing CS
            shift_reg <= command ? data_in[15:8] : 8'h00;
            bit_cnt <= 0;
            byte_cnt <= 0;
            recv_data <= 0;
            spi_mosi <= 0;
            state <= command ? WRITE_DATA : READ_DATA;

            // Update previous address
            prev_addr <= addr;
          end
          else
          begin
            // End transaction
            state <= STOP;
          end
        end
        default :
          state <= STOP;

      endcase
    end

  end

endmodule

module interrupt_controller_small (
    input  [3:0] dOut,
    input  [15:0] Addr,
    input         ioW,
    input         C,
    input         rst_n,

    input  [2:0]  irq_in,
    input         imm,
    input         reti,
    input         pc_en,

    input  [15:0] CPUInterruptEnableAddr,
    input  [15:0] inputInterruptAddr,
    input  [15:0] interruptRegAddr,

    output [15:0] InterruptOut,
    output        intr,
    output        irq_lock
);

  reg       global_enable;
  reg       irq_lock_r   ;
  reg [2:0] irq_enable   ;
  reg [2:0] irq_pending  ;

  wire wr_ctrl;
  wire wr_enable;
  wire wr_pending;

  wire rd_ctrl;
  wire rd_enable;
  wire rd_pending;

  wire [2:0] pending_with_new_irq;
  wire [2:0] active_irq;
  wire       intr_take;

  assign wr_ctrl    = ioW && (Addr == CPUInterruptEnableAddr);
  assign wr_enable  = ioW && (Addr == inputInterruptAddr);
  assign wr_pending = ioW && (Addr == interruptRegAddr);

  assign rd_ctrl    =  (Addr == CPUInterruptEnableAddr);
  assign rd_enable  =  (Addr == inputInterruptAddr);
  assign rd_pending =  (Addr == interruptRegAddr);

  assign pending_with_new_irq = irq_pending | irq_in;
  assign active_irq           = irq_pending & irq_enable;

  assign intr      = global_enable && !irq_lock_r && !imm && (active_irq != 4'b0000);
  assign irq_lock  = irq_lock_r;
  assign intr_take = intr && pc_en;

  always @(posedge C or negedge rst_n)
  begin
    if (!rst_n)
    begin
      global_enable <= 1'b0;
      irq_lock_r    <= 1'b0;
      irq_enable    <= 4'b0000;
      irq_pending   <= 4'b0000;
    end
    else
    begin
      // default: latch new interrupt requests
      irq_pending <= pending_with_new_irq;

      // global interrupt enable
      if (wr_ctrl)
        global_enable <= dOut[0];

      // source enable bits [3:0]
      if (wr_enable)
        irq_enable <= dOut[3:0];

      // write 1 to clear pending bits
      if (wr_pending)
        irq_pending <= pending_with_new_irq & ~dOut[2:0];

      // lock once interrupt is actually taken
      if (intr_take)
        irq_lock_r <= 1'b1;

      // unlock only on RETI
      if (reti)
        irq_lock_r <= 1'b0;
    end
  end

  assign InterruptOut =
      rd_ctrl    ? {13'h0000, intr, irq_lock_r, global_enable} :
      rd_enable  ? {13'h000, irq_enable} :
      rd_pending ? {13'h000, irq_pending} :
      16'h0000;

endmodule
module lfsr_RandomNumberGen (
    input  [15:0] adrrIn,
    input  [7:0] dataIn,
    input         ioW,
    input         clk,
    input  [15:0] SeedAdr,
    input  [15:0] RngAdr,
    output [15:0] Out
);

    reg [7:0] seed_reg;
    reg [7:0] lfsr    ;

    wire seed_wr  = ioW && (adrrIn == SeedAdr);
    wire seed_rd  =  (adrrIn == SeedAdr);
    wire rng_rd   =  (adrrIn == RngAdr);

    // 8-bit maximal-length taps
    // polynomial: x^8 + x^6 + x^5 + x^4 + 1
    wire feedback = lfsr[7] ^ lfsr[5] ^ lfsr[4] ^ lfsr[3];

    always @(posedge clk) begin
        if (seed_wr) begin
            seed_reg <= dataIn[7:0];
            lfsr <= (dataIn[7:0] == 8'h00) ? 8'h01 : dataIn[7:0];
        end else begin
            lfsr <= {lfsr[6:0], feedback};
        end
    end

    assign Out = seed_rd ? {8'h00, seed_reg} :
                 rng_rd  ? {8'h00, lfsr}     :
                           16'h0000;

endmodule
module timer (
    input  [15:0] dOut,
    input  [15:0] Addr,
    input         ioW,
    input         C,
    input         InterLock,
    input  [15:0] timerConfigAddr,
    input  [15:0] timerTargetAddr,
    input  [15:0] timerResetAddr,
    input  [15:0] timerReadAddr,
    input  [15:0] timerSyncStartAddr,
    input         rst_n,
    output [15:0] TimerOut,
    output        timer_interrupt
  );

  reg [15:0] target       ;
  reg [15:0] count        ;
  reg [10:0] prescale_cnt ;
  reg [6:0]  conf         ;

  wire wr_conf   = ioW && (Addr == timerConfigAddr);
  wire wr_target = ioW && (Addr == timerTargetAddr);
  wire wr_reset  = ioW && (Addr == timerResetAddr) && dOut[0];
  wire wr_sync_start = ioW && (Addr == timerSyncStartAddr);

  wire rd_count  =  (Addr == timerReadAddr);
  wire rd_target =  (Addr == timerTargetAddr);
  wire rd_conf   =  (Addr == timerConfigAddr);

  wire       timer_en     = conf[0];
  wire [3:0] prescaler    = conf[4:1];
  wire       auto_reload  = conf[5];
  wire       irq_en       = conf[6];
  wire       target_valid = (target != 16'h0000);
  wire       matched      = target_valid && (count == target);

  reg tick;
  always @(*)
  begin
    case (prescaler)
      4'd0:
        tick = 1'b1;                  // /1
      4'd1:
        tick = prescale_cnt[0];       // /2
      4'd2:
        tick = &prescale_cnt[1:0];    // /4
      4'd3:
        tick = &prescale_cnt[2:0];    // /8
      4'd4:
        tick = &prescale_cnt[3:0];    // /16
      4'd5:
        tick = &prescale_cnt[4:0];    // /32
      4'd6:
        tick = &prescale_cnt[5:0];    // /64
      4'd7:
        tick = &prescale_cnt[6:0];    // /128
      4'd8:
        tick = &prescale_cnt[7:0];    // /256
      4'd9:
        tick = &prescale_cnt[8:0];    // /512
      4'd10:
        tick = &prescale_cnt[9:0];    // /1024
      default:
        tick = 1'b1;
    endcase
  end

  always @(posedge C or negedge rst_n)
  begin
    if (!rst_n)
    begin
      target       <= 16'h0000;
      count        <= 16'h0000;
      prescale_cnt <= 11'h000;
      conf         <= 7'h00;
    end
    else
    begin
      if (wr_conf)
      begin
        conf         <= dOut[6:0];
        prescale_cnt <= 11'h000;
      end

      if (wr_target)
        target <= dOut;

      if (wr_sync_start)
        conf[0] <= dOut[0];

      if (wr_reset)
      begin
        count        <= 16'h0000;
        conf         <=7'h00;
      end
      else
      begin
        if (timer_en)
          prescale_cnt <= prescale_cnt + 11'd1;

        if (timer_en && !InterLock)
        begin
          if (matched)
          begin
            if (auto_reload)
              count <= 16'h0000;
          end
          else if (tick)
          begin
            count <= count + 16'd1;
          end
        end
      end
    end
  end

  assign TimerOut = rd_count  ? count             :
         rd_target ? target            :
         rd_conf   ? {9'h000, conf}   :
         16'h0000;

  assign timer_interrupt = irq_en && !InterLock && matched;

endmodule

module timer_tiny (
    input  [8:0] dOut,
    input  [15:0] Addr,
    input         ioW,
    input         C,
    input         InterLock,
    input  [15:0] timerConfigAddr,
    input  [15:0] timerTargetAddr,
    input  [15:0] timerResetAddr,
    input  [15:0] timerReadAddr,
    input  [15:0] timerSyncStartAddr,
    input         rst_n,
    output [15:0] TimerOut,
    output        timer_interrupt
  );

  reg [8:0] target        ;
  reg [8:0] count         ;
  reg [10:0] prescale_cnt  ;
  reg [6:0]  conf         ;

  wire wr_conf   = ioW && (Addr == timerConfigAddr);
  wire wr_target = ioW && (Addr == timerTargetAddr);
  wire wr_reset  = ioW && (Addr == timerResetAddr) && dOut[0];
  wire wr_sync_start = ioW && (Addr == timerSyncStartAddr);

  wire rd_count  = (Addr == timerReadAddr);
  wire rd_target = (Addr == timerTargetAddr);
  wire rd_conf   = (Addr == timerConfigAddr);

  wire       timer_en     = conf[0];
  wire [3:0] prescaler    = conf[4:1];
  wire       auto_reload  = conf[5];
  wire       irq_en       = conf[6];
  wire       target_valid = (target != 16'h0000);
  wire       matched      = target_valid && (count == target);

  reg tick;
  always @(*)
  begin
    case (prescaler)
      4'd0:
        tick = 1'b1;                  // /1
      4'd1:
        tick = prescale_cnt[0];       // /2
      4'd2:
        tick = &prescale_cnt[1:0];    // /4
      4'd3:
        tick = &prescale_cnt[2:0];    // /8
      4'd4:
        tick = &prescale_cnt[3:0];    // /16
      4'd5:
        tick = &prescale_cnt[4:0];    // /32
      4'd6:
        tick = &prescale_cnt[5:0];    // /64
      4'd7:
        tick = &prescale_cnt[6:0];    // /128
      4'd8:
        tick = &prescale_cnt[7:0];    // /256
      4'd9:
        tick = &prescale_cnt[8:0];    // /512
      4'd10:
        tick = &prescale_cnt[9:0];    // /1024
      4'd11:
        tick = &prescale_cnt[10:0];   // /2048
      default:
        tick = 1'b1;
    endcase
  end

  always @(posedge C or negedge rst_n)
  begin
    if (!rst_n)
    begin
      target       <= 8'h00;
      count        <= 8'h00;
      prescale_cnt <= 11'h000;
      conf         <= 7'h00;
    end
    else
    begin
      if (wr_conf)
      begin
        conf         <= dOut[6:0];
        prescale_cnt <= 11'h000;
      end

      if (wr_target)
        target <= dOut[8:0];

      if (wr_sync_start)
        conf[0] <= dOut[0];

      if (wr_reset)
      begin
        count        <= 8'h00;
        conf        <=7'h00;
      end
      else
      begin
        if (timer_en)
          prescale_cnt <= prescale_cnt + 11'd1;

        if (timer_en && !InterLock)
        begin
          if (matched)
          begin
            if (auto_reload)
              count <= 8'h00;
          end
          else if (tick)
          begin
            count <= count + 8'd1;
          end
        end
      end
    end
  end

  assign TimerOut = rd_count  ? {8'h0, count }            :
         rd_target ? {8'h0, target }            :
         rd_conf   ? {9'h000, conf}   :
         16'h0000;

  assign timer_interrupt = irq_en && !InterLock && matched;

endmodule

module RegisterBlock (
    input  [15:0] DataIn,
    input         WE,
    input         clk,
    input  [3:0]  src,
    input  [3:0]  Dest,
    output [15:0] RDest,
    output [15:0] Rsrc
  );

  reg [15:0] regs [0:15];

  always @(negedge clk )
  begin

    if (WE)
    begin
      regs[Dest] <= DataIn;
    end
  end

  // read ports
  assign Rsrc  = regs[src];
  assign RDest = regs[Dest];

endmodule


module Mux_8x1_NBits #(
    parameter Bits = 2
)
(
    input [2:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule

module i2c_master_ctrl (
    input              clk,
    input              rst_n,

    input              wr_en,
    input      [3:0]   reg_addr,
    input      [15:0]  cpu_din,
    output reg [15:0]  cpu_dout,

    input              sda_in,
    input              scl_in,
    output             sda_out,
    output             scl_out,
    output reg         sda_oe,
    output reg         scl_oe,

    output             interrupt
);

assign sda_out = 1'b0;
assign scl_out = 1'b0;
assign interrupt = irq_enable & irq_pending;

localparam ST_IDLE       = 4'd0;
localparam ST_START_1    = 4'd1;
localparam ST_START_2    = 4'd2;
localparam ST_START_3    = 4'd3;
localparam ST_BIT_SETUP  = 4'd4;
localparam ST_BIT_HIGH   = 4'd5;
localparam ST_BIT_LOW    = 4'd6;
localparam ST_ACK_SETUPW = 4'd7;
localparam ST_ACK_HIGHW  = 4'd8;
localparam ST_ACK_LOWW   = 4'd9;
localparam ST_ACK_SETUPR = 4'd10;
localparam ST_ACK_HIGHR  = 4'd11;
localparam ST_ACK_LOWR   = 4'd12;
localparam ST_STOP_1     = 4'd13;
localparam ST_STOP_2     = 4'd14;
localparam ST_STOP_3     = 4'd15;

reg        enable;
reg        irq_enable;
reg        stretch_enable;

reg        op_busy;
reg        bus_active;
reg        done;
reg        ack_error;
reg        rx_valid;
reg        irq_pending;

reg [15:0] prescale_reg;
reg [15:0] divcnt;
reg        sm_tick;

reg [7:0]  tx_data_reg;
reg [7:0]  rx_data_reg;

reg [7:0]  tx_shift;
reg [7:0]  rx_shift;
reg [3:0]  bit_count;

reg        cmd_start;
reg        cmd_stop;
reg        cmd_write;
reg        cmd_read;
reg        cmd_read_nack;

reg [3:0]  state;

wire launch_cmd;
assign launch_cmd = wr_en && (reg_addr == 4'h4) && !op_busy && enable &&
                    (cpu_din[0] || cpu_din[1] || cpu_din[2] || cpu_din[3]);

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        enable         <= 1'b0;
        irq_enable     <= 1'b0;
        stretch_enable <= 1'b0;

        op_busy        <= 1'b0;
        bus_active     <= 1'b0;
        done           <= 1'b0;
        ack_error      <= 1'b0;
        rx_valid       <= 1'b0;
        irq_pending    <= 1'b0;

        prescale_reg   <= 16'd0;
        divcnt         <= 16'd0;
        sm_tick        <= 1'b0;

        tx_data_reg    <= 8'd0;
        rx_data_reg    <= 8'd0;
        tx_shift       <= 8'd0;
        rx_shift       <= 8'd0;
        bit_count      <= 4'd0;

        cmd_start      <= 1'b0;
        cmd_stop       <= 1'b0;
        cmd_write      <= 1'b0;
        cmd_read       <= 1'b0;
        cmd_read_nack  <= 1'b0;

        state          <= ST_IDLE;

        sda_oe         <= 1'b0;
        scl_oe         <= 1'b0;
    end else begin
        sm_tick <= 1'b0;

        if (op_busy) begin
            if (prescale_reg == 16'd0) begin
                sm_tick <= 1'b1;
            end else begin
                if (divcnt == 16'd0) begin
                    divcnt  <= prescale_reg;
                    sm_tick <= 1'b1;
                end else begin
                    divcnt <= divcnt - 16'd1;
                end
            end
        end else begin
            divcnt <= 16'd0;
        end

        if (wr_en) begin
            case (reg_addr)
                4'h0: begin
                    enable         <= cpu_din[0];
                    irq_enable     <= cpu_din[1];
                    stretch_enable <= cpu_din[2];
                end

                4'h1: begin
                    if (cpu_din[2]) done        <= 1'b0;
                    if (cpu_din[3]) ack_error   <= 1'b0;
                    if (cpu_din[4]) rx_valid    <= 1'b0;
                    if (cpu_din[5]) irq_pending <= 1'b0;
                end

                4'h2: begin
                    prescale_reg <= cpu_din;
                end

                4'h3: begin
                    tx_data_reg <= cpu_din[7:0];
                end
                default:begin

                    
                end
            endcase
        end

        if (launch_cmd) begin
            cmd_start     <= cpu_din[0];
            cmd_stop      <= cpu_din[1];
            cmd_write     <= cpu_din[2];
            cmd_read      <= cpu_din[3];
            cmd_read_nack <= cpu_din[4];

            done        <= 1'b0;
            ack_error   <= 1'b0;
            irq_pending <= 1'b0;

            tx_shift    <= tx_data_reg;
            rx_shift    <= 8'd0;
            bit_count   <= 4'd7;
            op_busy     <= 1'b1;

            if (cpu_din[0]) begin
                state  <= ST_START_1;
                sda_oe <= 1'b0;
                scl_oe <= 1'b0;
            end else if (cpu_din[2] || cpu_din[3]) begin
                state <= ST_BIT_SETUP;
                scl_oe <= 1'b1;
            end else if (cpu_din[1]) begin
                state  <= ST_STOP_1;
                sda_oe <= 1'b1;
                scl_oe <= 1'b1;
            end else begin
                op_busy <= 1'b0;
                done    <= 1'b1;
                irq_pending <= 1'b1;
                state   <= ST_IDLE;
            end
        end

        if (sm_tick && op_busy) begin
            case (state)
                ST_IDLE: begin
                    op_busy <= 1'b0;
                end

                ST_START_1: begin
                    sda_oe <= 1'b0;
                    scl_oe <= 1'b0;
                    if (sda_in && ((!stretch_enable) || scl_in)) begin
                        state <= ST_START_2;
                    end
                end

                ST_START_2: begin
                    sda_oe <= 1'b1; // SDA low while SCL high
                    scl_oe <= 1'b0;
                    state  <= ST_START_3;
                end

                ST_START_3: begin
                    scl_oe     <= 1'b1; // pull SCL low
                    bus_active <= 1'b1;

                    if (cmd_write || cmd_read) begin
                        state <= ST_BIT_SETUP;
                    end else if (cmd_stop) begin
                        state <= ST_STOP_1;
                    end else begin
                        done        <= 1'b1;
                        irq_pending <= 1'b1;
                        op_busy     <= 1'b0;
                        state       <= ST_IDLE;
                    end
                end

                ST_BIT_SETUP: begin
                    scl_oe <= 1'b1; // keep clock low during setup

                    if (cmd_write) begin
                        if (tx_shift[bit_count])
                            sda_oe <= 1'b0; // release for logic 1
                        else
                            sda_oe <= 1'b1; // drive low for logic 0
                    end else begin
                        sda_oe <= 1'b0; // read bit: release SDA
                    end

                    state <= ST_BIT_HIGH;
                end

                ST_BIT_HIGH: begin
                    scl_oe <= 1'b0; // release SCL high

                    if ((!stretch_enable) || scl_in) begin
                        if (cmd_read)
                            rx_shift[bit_count] <= sda_in;

                        state <= ST_BIT_LOW;
                    end
                end

                ST_BIT_LOW: begin
                    scl_oe <= 1'b1; // drive SCL low again

                    if (bit_count != 4'd0) begin
                        bit_count <= bit_count - 4'd1;
                        state     <= ST_BIT_SETUP;
                    end else begin
                        if (cmd_write)
                            state <= ST_ACK_SETUPW;
                        else
                            state <= ST_ACK_SETUPR;
                    end
                end

                ST_ACK_SETUPW: begin
                    sda_oe <= 1'b0; // slave drives ACK/NACK
                    scl_oe <= 1'b1;
                    state  <= ST_ACK_HIGHW;
                end

                ST_ACK_HIGHW: begin
                    scl_oe <= 1'b0;

                    if ((!stretch_enable) || scl_in) begin
                        if (sda_in)
                            ack_error <= 1'b1;

                        state <= ST_ACK_LOWW;
                    end
                end

                ST_ACK_LOWW: begin
                    scl_oe <= 1'b1;
                    sda_oe <= 1'b0;

                    if (cmd_stop) begin
                        state <= ST_STOP_1;
                    end else begin
                        done        <= 1'b1;
                        irq_pending <= 1'b1;
                        op_busy     <= 1'b0;
                        state       <= ST_IDLE;
                    end
                end

                ST_ACK_SETUPR: begin
                    scl_oe <= 1'b1;

                    if (cmd_read_nack)
                        sda_oe <= 1'b0; // NACK = release high
                    else
                        sda_oe <= 1'b1; // ACK = drive low

                    state <= ST_ACK_HIGHR;
                end

                ST_ACK_HIGHR: begin
                    scl_oe <= 1'b0;

                    if ((!stretch_enable) || scl_in) begin
                        state <= ST_ACK_LOWR;
                    end
                end

                ST_ACK_LOWR: begin
                    scl_oe      <= 1'b1;
                    sda_oe      <= 1'b0;
                    rx_data_reg <= rx_shift;
                    rx_valid    <= 1'b1;

                    if (cmd_stop) begin
                        state <= ST_STOP_1;
                    end else begin
                        done        <= 1'b1;
                        irq_pending <= 1'b1;
                        op_busy     <= 1'b0;
                        state       <= ST_IDLE;
                    end
                end

                ST_STOP_1: begin
                    sda_oe <= 1'b1; // SDA low
                    scl_oe <= 1'b1; // SCL low
                    state  <= ST_STOP_2;
                end

                ST_STOP_2: begin
                    sda_oe <= 1'b1; // keep SDA low
                    scl_oe <= 1'b0; // release SCL high

                    if ((!stretch_enable) || scl_in) begin
                        state <= ST_STOP_3;
                    end
                end

                ST_STOP_3: begin
                    sda_oe      <= 1'b0; // release SDA high
                    scl_oe      <= 1'b0;
                    bus_active  <= 1'b0;
                    done        <= 1'b1;
                    irq_pending <= 1'b1;
                    op_busy     <= 1'b0;
                    state       <= ST_IDLE;
                end

                default: begin
                    sda_oe      <= 1'b0;
                    scl_oe      <= 1'b0;
                    bus_active  <= 1'b0;
                    done        <= 1'b1;
                    ack_error   <= 1'b1;
                    irq_pending <= 1'b1;
                    op_busy     <= 1'b0;
                    state       <= ST_IDLE;
                end
            endcase
        end
    end
end

always @(*) begin
    cpu_dout = 16'd0;

    case (reg_addr)
        4'h0: begin
            cpu_dout[0] = enable;
            cpu_dout[1] = irq_enable;
            cpu_dout[2] = stretch_enable;
        end

        4'h1: begin
            cpu_dout[0] = op_busy;
            cpu_dout[1] = bus_active;
            cpu_dout[2] = done;
            cpu_dout[3] = ack_error;
            cpu_dout[4] = rx_valid;
            cpu_dout[5] = irq_pending;
        end

        4'h2: begin
            cpu_dout = prescale_reg;
        end

        4'h3: begin
            cpu_dout[7:0] = rx_data_reg;
        end

        4'h4: begin
            cpu_dout[0] = cmd_start;
            cpu_dout[1] = cmd_stop;
            cpu_dout[2] = cmd_write;
            cpu_dout[3] = cmd_read;
            cpu_dout[4] = cmd_read_nack;
        end

        default: begin
            cpu_dout = 16'd0;
        end
    endcase
end

endmodule
module debug_serial_frontend_tiny
(
    input  wire        cpu_clk,
    input  wire        rst_n,

    input  wire        dbg_clk,
    input  wire        dbg_data_in,
    output reg         dbg_data_out,
    output reg         dbg_data_oe,

    output reg         reg_wr,
    output reg  [3:0]  reg_addr,
    output reg  [15:0] reg_wdata,
    input  wire [15:0] reg_rdata
);

  localparam CMD_PING  = 4'h0;
  localparam CMD_READ  = 4'h1;
  localparam CMD_WRITE = 4'h2;

  localparam S_RX      = 2'd0;
  localparam S_EXEC    = 2'd1;
  localparam S_LOAD_TX = 2'd2;
  localparam S_TX      = 2'd3;

  reg [1:0]  state;
  reg [23:0] rx_shift;
  reg [4:0]  rx_count;
  reg [15:0] tx_shift;
  reg [4:0]  tx_count;

  reg [3:0]  cmd_hold;
  reg [3:0]  addr_hold;
  reg [15:0] wdata_hold;

  reg [1:0] dbg_clk_sync;
  reg [1:0] dbg_data_sync;

  wire dbg_clk_rise;
  wire dbg_clk_fall;
  wire [23:0] rx_next;
  wire [15:0] tx_word;

  assign dbg_clk_rise = (dbg_clk_sync == 2'b01);
  assign dbg_clk_fall = (dbg_clk_sync == 2'b10);
  assign rx_next      = {rx_shift[22:0], dbg_data_sync[1]};
  assign tx_word      = (cmd_hold == CMD_PING)  ? 16'hDB12 :
                        (cmd_hold == CMD_READ)  ? reg_rdata :
                        (cmd_hold == CMD_WRITE) ? 16'hACCE :
                                                  16'hEEEE;

  always @(posedge cpu_clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      state        <= S_RX;
      rx_shift     <= 24'h000000;
      rx_count     <= 5'd0;
      tx_shift     <= 16'h0000;
      tx_count     <= 5'd0;
      cmd_hold     <= 4'h0;
      addr_hold    <= 4'h0;
      wdata_hold   <= 16'h0000;
      dbg_clk_sync <= 2'b00;
      dbg_data_sync<= 2'b11;
      dbg_data_out <= 1'b1;
      dbg_data_oe  <= 1'b0;
      reg_wr       <= 1'b0;
      reg_addr     <= 4'h0;
      reg_wdata    <= 16'h0000;
    end
    else
    begin
      dbg_clk_sync  <= {dbg_clk_sync[0], dbg_clk};
      dbg_data_sync <= {dbg_data_sync[0], dbg_data_in};
      reg_wr        <= 1'b0;

      case (state)
        S_RX:
        begin
          dbg_data_oe  <= 1'b0;
          dbg_data_out <= 1'b1;

          if (dbg_clk_rise)
          begin
            if (rx_count == 5'd23)
            begin
              cmd_hold   <= rx_next[23:20];
              addr_hold  <= rx_next[19:16];
              wdata_hold <= rx_next[15:0];
              rx_count   <= 5'd0;
              state      <= S_EXEC;
            end
            else
            begin
              rx_shift <= rx_next;
              rx_count <= rx_count + 5'd1;
            end
          end
        end

        S_EXEC:
        begin
          reg_addr  <= addr_hold;
          reg_wdata <= wdata_hold;
          if (cmd_hold == CMD_WRITE)
            reg_wr <= 1'b1;
          state <= S_LOAD_TX;
        end

        S_LOAD_TX:
        begin
          tx_shift     <= tx_word;
          tx_count     <= 5'd0;
          dbg_data_oe  <= 1'b0;
          dbg_data_out <= 1'b1;

          if (dbg_clk_fall)
          begin
            dbg_data_oe  <= 1'b1;
            dbg_data_out <= tx_word[15];
            state        <= S_TX;
          end
        end

        S_TX:
        begin
          if (dbg_clk_fall)
          begin
            if (tx_count == 5'd15)
            begin
              dbg_data_oe  <= 1'b0;
              dbg_data_out <= 1'b1;
              state        <= S_RX;
            end
            else
            begin
              tx_shift     <= {tx_shift[14:0], 1'b0};
              dbg_data_out <= tx_shift[14];
              tx_count     <= tx_count + 5'd1;
            end
          end
        end

        default:
        begin
          state        <= S_RX;
          dbg_data_oe  <= 1'b0;
          dbg_data_out <= 1'b1;
        end
      endcase
    end
  end

endmodule

module cpu_cycle_controller_tiny
(
    input  wire clk,
    input  wire rst_n,

    input  wire fetch_done,
    input  wire data_done,

    input  wire ld,
    input  wire st,
    input  wire flash_ld,

    input  wire dbg_enable,
    input  wire dbg_halt_req,
    input  wire dbg_run_req,
    input  wire dbg_step_req,
    input  wire dbg_break_hit,
    input  wire dbg_break_after_exec,

    output wire fetch_req,
    output wire execute_now_pulse,
    output wire dbg_halted
);

  localparam S_REQ_FETCH  = 3'd0;
  localparam S_WAIT_FETCH = 3'd1;
  localparam S_EXECUTE    = 3'd2;
  localparam S_WAIT_DATA  = 3'd3;
  localparam S_HALTED     = 3'd4;

  reg [2:0] state;
  reg       halt_pending;
  reg       step_active;

  wire mem_op;
  wire stop_after_exec;

  assign mem_op           = ld | st | flash_ld;
  assign fetch_req        = (state == S_REQ_FETCH);
  assign execute_now_pulse= (state == S_EXECUTE);
  assign dbg_halted       = (state == S_HALTED);
  assign stop_after_exec  = dbg_enable & (halt_pending | step_active | dbg_break_after_exec);

  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      state        <= S_REQ_FETCH;
      halt_pending <= 1'b0;
      step_active  <= 1'b0;
    end
    else if (!dbg_enable)
    begin
      halt_pending <= 1'b0;
      step_active  <= 1'b0;

      case (state)
        S_REQ_FETCH:  state <= S_WAIT_FETCH;
        S_WAIT_FETCH: if (fetch_done) state <= S_EXECUTE;
        S_EXECUTE:    state <= mem_op ? S_WAIT_DATA : S_REQ_FETCH;
        S_WAIT_DATA:  if (data_done) state <= S_REQ_FETCH;
        default:      state <= S_REQ_FETCH;
      endcase
    end
    else
    begin
      if (dbg_halt_req)
        halt_pending <= 1'b1;

      case (state)
        S_REQ_FETCH:
        begin
          if (dbg_halt_req)
          begin
            state        <= S_HALTED;
            halt_pending <= 1'b0;
            step_active  <= 1'b0;
          end
          else
            state <= S_WAIT_FETCH;
        end

        S_WAIT_FETCH:
        begin
          if (fetch_done)
          begin
            if (dbg_break_hit | halt_pending)
            begin
              state        <= S_HALTED;
              halt_pending <= 1'b0;
              step_active  <= 1'b0;
            end
            else
              state <= S_EXECUTE;
          end
        end

        S_EXECUTE:
        begin
          if (mem_op)
            state <= S_WAIT_DATA;
          else if (stop_after_exec)
          begin
            state        <= S_HALTED;
            halt_pending <= 1'b0;
            step_active  <= 1'b0;
          end
          else
            state <= S_REQ_FETCH;
        end

        S_WAIT_DATA:
        begin
          if (data_done)
          begin
            if (stop_after_exec)
            begin
              state        <= S_HALTED;
              halt_pending <= 1'b0;
              step_active  <= 1'b0;
            end
            else
              state <= S_REQ_FETCH;
          end
        end

        S_HALTED:
        begin
          halt_pending <= 1'b0;

          if (dbg_run_req)
          begin
            state       <= S_REQ_FETCH;
            step_active <= 1'b0;
          end
          else if (dbg_step_req)
          begin
            state       <= S_REQ_FETCH;
            step_active <= 1'b1;
          end
        end

        default:
        begin
          state        <= S_REQ_FETCH;
          halt_pending <= 1'b0;
          step_active  <= 1'b0;
        end
      endcase
    end
  end

endmodule

module memory_wait_controller_tiny
(
    input  wire        clk,
    input  wire        rst_n,

    input  wire        fetch_req,
    input  wire        ld_req,
    input  wire        st_req,
    input  wire        flash_req,

    input  wire [15:0] fetch_addr,
    input  wire [15:0] data_addr,
    input  wire [15:0] store_data,

    output reg  [15:0] mem_rdata,
    output reg         fetch_done,
    output reg         data_done,
    output reg         mem_stall,

    output reg         spi_st,
    output reg         spi_ld,
    output reg  [15:0] spi_addr,
    output reg  [15:0] spi_data_in,
    output reg         spi_target,
    input  wire [15:0] spi_data_out,
    input  wire        spi_busy
);

  localparam OP_NONE  = 2'd0;
  localparam OP_FETCH = 2'd1;
  localparam OP_LOAD  = 2'd2;
  localparam OP_STORE = 2'd3;

  localparam S_IDLE           = 3'd0;
  localparam S_START          = 3'd1;
  localparam S_WAIT_BUSY_HIGH = 3'd2;
  localparam S_WAIT_BUSY_LOW  = 3'd3;
  localparam S_FINISH         = 3'd4;

  reg [2:0] state;
  reg [1:0] op;
  reg [15:0] last_flash_addr;


  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      state              <= S_IDLE;
      op                 <= OP_NONE;
      mem_rdata          <= 16'h0000;
      fetch_done         <= 1'b0;
      data_done          <= 1'b0;
      mem_stall          <= 1'b0;
      spi_st             <= 1'b0;
      spi_ld             <= 1'b0;
      spi_addr           <= 16'h0000;
      spi_data_in        <= 16'h0000;
      spi_target         <= 1'b0;
      last_flash_addr    <= 16'h0000;
    end
    else
    begin
      fetch_done <= 1'b0;
      data_done  <= 1'b0;
      spi_st     <= 1'b0;
      spi_ld     <= 1'b0;

      case (state)
        S_IDLE:
        begin
          mem_stall <= 1'b0;
          op        <= OP_NONE;

          if (st_req)
          begin
            op          <= OP_STORE;
            spi_target  <= 1'b1;
            spi_addr    <= data_addr;
            spi_data_in <= store_data;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
          else if (ld_req)
          begin
            op          <= OP_LOAD;
            spi_target  <= 1'b1;
            spi_addr    <= data_addr;
            spi_data_in <= 16'h0000;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
          else if (fetch_req)
          begin
            op          <= OP_FETCH;
            spi_target  <= 1'b0;
            spi_addr    <= fetch_addr;
            spi_data_in <= 16'h0000;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
          else if (flash_req)
          begin
            op          <= OP_LOAD;
            spi_target  <= 1'b0;
            spi_addr    <= data_addr;
            spi_data_in <= 16'h0000;
            mem_stall   <= 1'b1;
            state       <= S_START;
          end
        end

        S_START:
        begin
          if (op == OP_STORE)
            spi_st <= 1'b1;
          else
          begin
            spi_ld <= 1'b1;
            
          end
          state <= S_WAIT_BUSY_HIGH;
        end

        S_WAIT_BUSY_HIGH:
          if (spi_busy)
            state <= S_WAIT_BUSY_LOW;

        S_WAIT_BUSY_LOW:
        begin
          if (!spi_busy)
          begin
            if (op != OP_STORE)
              mem_rdata <= spi_data_out;
            state <= S_FINISH;
          end
        end

        S_FINISH:
        begin
          mem_stall <= 1'b0;
          if (op == OP_FETCH)
          begin
            fetch_done         <= 1'b1;
            last_flash_addr    <= spi_addr;
          end
          else
          begin
            data_done          <= 1'b1;
          end
          state <= S_IDLE;
        end

        default:
        begin
          state              <= S_IDLE;
        end
      endcase
    end
  end

endmodule

module debug_core_tiny
(
    input  wire        clk,
    input  wire        rst_n,

    // Tiny register port
    input  wire        reg_wr,
    input  wire [3:0]  reg_addr,
    input  wire [15:0] reg_wdata,
    output reg  [15:0] reg_rdata,

    // CPU status
    input  wire        cpu_dbg_halted,
    input  wire [2:0]  cpu_flags,
    input  wire [15:0] cpu_pc,
    input  wire [15:0] cpu_ir,

    // Debug control outputs
    output reg         dbg_enable,
    output reg         dbg_halt_req,
    output reg         dbg_run_req,
    output reg         dbg_step_req,
    output reg         static_break_enable,

    // One dynamic breakpoint only
    output reg  [15:0] bp0,
    output reg         bp_enable
);

  localparam REG_ID      = 4'h0;
  localparam REG_STATUS  = 4'h1;
  localparam REG_CONTROL = 4'h2;
  localparam REG_FLAGS   = 4'h3;
  localparam REG_PC      = 4'h4;
  localparam REG_IR      = 4'h5;
  localparam REG_BP0     = 4'h8;
  localparam REG_BPCTRL  = 4'h9;

  always @(posedge clk or negedge rst_n)
  begin
    if (!rst_n)
    begin
      dbg_enable           <= 1'b0;
      dbg_halt_req         <= 1'b0;
      dbg_run_req          <= 1'b0;
      dbg_step_req         <= 1'b0;
      static_break_enable  <= 1'b0;
      bp0                  <= 16'h0000;
      bp_enable            <= 1'b0;
    end
    else
    begin
      dbg_run_req  <= 1'b0;
      dbg_step_req <= 1'b0;

      if (cpu_dbg_halted)
        dbg_halt_req <= 1'b0;

      if (reg_wr)
      begin
        case (reg_addr)
          REG_CONTROL:
          begin
            dbg_enable          <= reg_wdata[0];
            static_break_enable <= reg_wdata[5];

            if (!reg_wdata[0])
              dbg_halt_req <= 1'b0;

            if (reg_wdata[1] && reg_wdata[0])
              dbg_halt_req <= 1'b1;

            if (reg_wdata[2] && reg_wdata[0])
            begin
              dbg_run_req  <= 1'b1;
              dbg_halt_req <= 1'b0;
            end

            if (reg_wdata[3] && reg_wdata[0])
            begin
              dbg_step_req <= 1'b1;
              dbg_halt_req <= 1'b0;
            end
          end

          REG_BP0:
            bp0 <= reg_wdata;

          REG_BPCTRL:
            bp_enable <= reg_wdata[0];

          default:
          begin
          end
        endcase
      end
    end
  end

  always @(*)
  begin
    case (reg_addr)
      REG_ID:
        reg_rdata = 16'hDB11;

      REG_STATUS:
        reg_rdata = {
          12'h000,
          bp_enable,
          static_break_enable,
          dbg_enable,
          cpu_dbg_halted
        };

      REG_CONTROL:
        reg_rdata = {
          10'h000,
          static_break_enable,
          1'b0,
          1'b0,
          1'b0,
          dbg_halt_req,
          dbg_enable
        };

      REG_FLAGS:
        reg_rdata = {13'h0000, cpu_flags};

      REG_PC:
        reg_rdata = cpu_pc;

      REG_IR:
        reg_rdata = cpu_ir;

      REG_BP0:
        reg_rdata = bp0;

      REG_BPCTRL:
        reg_rdata = {15'h0000, bp_enable};

      default:
        reg_rdata = 16'h0000;
    endcase
  end

endmodule

module breakpoint_logic_tiny
(
    input  wire        clk,
    input  wire        rst_n,

    input  wire        dbg_enable,
    input  wire        dbg_halted,
    input  wire        dbg_run_req,
    input  wire        dbg_step_req,
    input  wire        execute_now_pulse,

    input  wire [15:0] pc,
    input  wire [15:0] bp0,
    input  wire        bp_enable,

    input  wire        instr_is_brk,
    input  wire        static_break_enable,

    output wire        dbg_break_hit,
    output wire        dbg_break_after_exec
);

    reg bp_resume_mask;
    wire resume_cmd;
    wire bp_raw_hit;

    assign resume_cmd = dbg_run_req | dbg_step_req;
    assign bp_raw_hit = dbg_enable & bp_enable & (pc == bp0);

    assign dbg_break_hit = bp_raw_hit & ~bp_resume_mask;
    assign dbg_break_after_exec = dbg_enable & static_break_enable & instr_is_brk;

    always @(posedge clk or negedge rst_n)
    begin
        if (!rst_n)
            bp_resume_mask <= 1'b0;
        else if (execute_now_pulse)
            bp_resume_mask <= 1'b0;
        else if (dbg_halted & resume_cmd)
            bp_resume_mask <= 1'b1;
    end

endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module singExtend (
  input [7:0] inst,
  output [15:0] \4S , // The four bits taken from Rs.
  output [15:0] \8SD , // The eight bits taken from Rs,Rd with sign extension.
  output [15:0] \4D  // The four bits taken from Rd.

);
  wire s0;
  assign \4D [3:0] = inst[7:4];
  assign \4D [15:4] = 12'b0;
  assign \4S [3:0] = inst[3:0];
  assign \4S [15:4] = 12'b0;
  assign s0 = inst[7];
  assign \8SD [6:0] = inst[6:0];
  assign \8SD [7] = s0;
  assign \8SD [8] = s0;
  assign \8SD [9] = s0;
  assign \8SD [10] = s0;
  assign \8SD [11] = s0;
  assign \8SD [12] = s0;
  assign \8SD [13] = s0;
  assign \8SD [14] = s0;
  assign \8SD [15] = s0;
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module opcode_microcode_rom(
    input  [6:0] opcode,
    output muxb0,
    output muxb1,
    output muxb2,
    output aluop0,
    output aluop1,
    output aluop2,
    output aluop3,
    output aluop4,
    output aluop5,
    output WE,
    output sf,
    output iem0,
    output iem1,
    output br0,
    output br1,
    output br2,
    output muxA,
    output ld,
    output st,
    output abs,
    output ioW,
    output ioR,
    output stPC,
    output Reti,
    output flash_req,
    output Brk
);

reg [24:0] ctrl;

assign {
    muxb0,
    muxb1,
    muxb2,
    aluop0,
    aluop1,
    aluop2,
    aluop3,
    aluop4,
    aluop5,
    WE,
    sf,
    iem0,
    iem1,
    br0,
    br1,
    br2,
    muxA,
    ld,
    st,
    abs,
    ioW,
    ioR,
    stPC,
    Reti,
    flash_req,
    Brk
} = ctrl;

always @(*) begin
    case (opcode)
        7'b0000000: ctrl = 26'b0000_0000_0000_0000_0000_00000_0;//8'hx00:
        7'b0000001: ctrl = 26'b0000_0000_0100_0000_1000_00000_0;//8'hx01:
        7'b0000010: ctrl = 26'b0000_0000_1110_0000_0000_00000_0;//8'hx02:
        7'b0000011: ctrl = 26'b0001_0000_1110_0000_0000_00000_0;//8'hx03:
        7'b0000100: ctrl = 26'b0000_0001_0110_0000_0000_00000_0;//8'hx04:
        7'b0000101: ctrl = 26'b0001_0001_0110_0000_0000_00000_0;//8'hx05:
        7'b0000110: ctrl = 26'b0000_0001_1110_0000_0000_00000_0;//8'hx06:
        7'b0000111: ctrl = 26'b0000_0010_0110_0000_0000_00000_0;//8'hx07:
        7'b0001000: ctrl = 26'b0000_0010_1110_0000_0000_00000_0;//8'hx08:
        7'b0001001: ctrl = 26'b0100_0000_0101_0000_0000_00000_0;//8'hx09:
        7'b0001010: ctrl = 26'b1010_0000_0100_0000_0000_00000_0;//8'hx0A:
        7'b0001011: ctrl = 26'b0100_0000_1111_0000_0000_00000_0;//8'hx0B:
        7'b0001100: ctrl = 26'b1010_0000_1110_0000_0000_00000_0;//8'hx0C:
        7'b0001101: ctrl = 26'b0101_0000_1111_0000_0000_00000_0;//8'hx0D:
        7'b0001110: ctrl = 26'b1011_0000_1110_0000_0000_00000_0;//8'hx0E:
        7'b0001111: ctrl = 26'b0100_0001_0111_0000_0000_00000_0;//8'hx0F:
        7'b0010000: ctrl = 26'b1010_0001_0110_0000_0000_00000_0;//8'hx10:
        7'b0010001: ctrl = 26'b0101_0001_0111_0000_0000_00000_0;//8'hx11:
        7'b0010010: ctrl = 26'b1011_0001_0110_0000_0000_00000_0;//8'hx12:
        7'b0010011: ctrl = 26'b0000_0011_1100_0000_0000_00000_0;//8'hx13:
        7'b0010100: ctrl = 26'b0100_0001_1111_0000_0000_00000_0;//8'hx14:
        7'b0010101: ctrl = 26'b1010_0001_1110_0000_0000_00000_0;//8'hx15:
        7'b0010110: ctrl = 26'b0100_0010_0111_0000_0000_00000_0;//8'hx16:
        7'b0010111: ctrl = 26'b1010_0010_0110_0000_0000_00000_0;//8'hx17:
        7'b0011000: ctrl = 26'b0100_0010_1111_0000_0000_00000_0;//8'hx18:
        7'b0011001: ctrl = 26'b1010_0010_1110_0000_0000_00000_0;//8'hx19:
        7'b0011010: ctrl = 26'b0000_0011_0100_0000_0000_00000_0;//8'hx1A:
        //17'b0011011:ctrl =58'b0000_0110_1110_0000_0000_00000;//8'hx1B:
        //17'b0011100:ctrl =58'b0100_0110_1111_0000_0000_00000;//8'hx1C:
        //17'b0011101:ctrl =58'b1010_0110_1110_0000_0000_00000;//8'hx1D:
        7'b0011110: ctrl = 26'b0000_0001_0010_0000_0000_00000_0;//8'hx1E:
        7'b0011111: ctrl = 26'b0001_0001_0010_0000_0000_00000_0;//8'hx1F:
        7'b0100000: ctrl = 26'b0100_0001_0011_0000_0000_00000_0;//8'hx20:
        7'b0100001: ctrl = 26'b1010_0001_0010_0000_0000_00000_0;//8'hx21:
        7'b0100010: ctrl = 26'b0101_0001_0011_0000_0000_00000_0;//8'hx22:
        7'b0100011: ctrl = 26'b1011_0001_0010_0000_0000_00000_0;//8'hx23:
        7'b0100100: ctrl = 26'b0000_0100_0110_0000_0000_00000_0;//8'hx24:
        7'b0100101: ctrl = 26'b0000_0100_1110_0000_0000_00000_0;//8'hx25:
        7'b0100110: ctrl = 26'b0001_0100_0110_0000_0000_00000_0;//8'hx26:
        7'b0100111: ctrl = 26'b0001_0100_1110_0000_0000_00000_0;//8'hx27:
        7'b0101000: ctrl = 26'b0000_0101_0110_0000_0000_00000_0;//8'hx28:
        7'b0101001: ctrl = 26'b0000_0101_1100_0000_0000_00000_0;//8'hx29:
        7'b0101010: ctrl = 26'b0000_0110_0100_0000_0000_00000_0;//8'hx2A:
        7'b0101011: ctrl = 26'b0110_0000_1000_0000_0010_00000_0;//8'hx2B:
        7'b0101100: ctrl = 26'b0110_0000_1100_0000_1100_00000_0;//8'hx2C:
        7'b0101101: ctrl = 26'b0100_0000_0001_1000_0010_00000_0;//8'hx2D:
        7'b0101110: ctrl = 26'b1110_0000_0000_0000_0010_00000_0;//8'hx2E:
        7'b0101111: ctrl = 26'b0100_0000_0101_0000_0100_00000_0;//8'hx2F:
        7'b0110000: ctrl = 26'b1010_0000_0100_0000_0100_00000_0;//8'hx30:
        7'b0110001: ctrl = 26'b0100_0000_1000_0000_0010_00000_0;//8'hx31:
        7'b0110010: ctrl = 26'b0100_0000_1100_0000_1100_00000_0;//8'hx32:
        //7'b0110011: ctrl = 26'b0010_0000_0100_0000_0000_000_000;//8'hx33:
        7'b0110100: ctrl = 26'b0100_0000_0001_0001_0000_00000_0;//8'hx34:
        7'b0110101: ctrl = 26'b0100_0000_0001_0010_0000_00000_0;//8'hx35:
        7'b0110110: ctrl = 26'b0100_0000_0001_0011_0000_00000_0;//8'hx36:
        7'b0110111: ctrl = 26'b0100_0000_0001_0101_0000_00000_0;//8'hx37:
        7'b0111000: ctrl = 26'b0100_0000_0001_0110_0000_00000_0;//8'hx38:
        7'b0111001: ctrl = 26'b0100_0000_0001_0111_0000_00000_0;//8'hx39:
        7'b0111010: ctrl = 26'b0100_0000_0101_0000_0001_00100_0;//8'hx3A:
        7'b0111011: ctrl = 26'b0000_0000_0000_0000_0001_00000_0;//8'hx3B:
        7'b0111100: ctrl = 26'b0100_0000_0001_0000_0001_00000_0;//8'hx3C:
        7'b0111101: ctrl = 26'b1100_0000_0000_0100_0000_00000_0;//8'hx3D:
        7'b0111110: ctrl = 26'b0100_0000_0001_1000_0000_10000_0;//8'hx3E:
        7'b0111111: ctrl = 26'b1110_0000_0000_0000_0000_10000_0;//8'hx3F:
        7'b1000000: ctrl = 26'b0110_0000_1000_0000_0000_10000_0;//8'hx40:
        7'b1000001: ctrl = 26'b0100_0000_0101_0000_1000_01000_0;//8'hx41:
        7'b1000010: ctrl = 26'b1010_0000_0100_0000_1000_01000_0;//8'hx42:
        7'b1000011: ctrl = 26'b0110_0000_1100_0000_1000_01000_0;//8'hx43:
        7'b1000100: ctrl = 26'b0000_0000_0000_0000_0001_00010_0;//8'hx44:
        7'b1000101: ctrl = 26'b0110_0000_1100_0000_1000_00001_0;//8'hx45:
        7'b1000110: ctrl = 26'b0100_0000_0101_0000_0000_00001_0;//8'hx46:
        7'b1000111: ctrl = 26'b1010_0000_0100_0000_0000_00001_0;//8'hx47:
        7'b1001000: ctrl = 26'b0100_0000_1100_0000_1000_00001_0;//8'hx48:
        7'b1001000: ctrl = 26'b0000_0000_0000_0000_0000_00000_1;//8'hx49:

        default:    ctrl = 26'b0000_0000_0000_0000_0000_00000_0;
    endcase
end

endmodule
module muxEncoder
  (
    input a,
    input b,
    input c,
    input d,
    output reg [1:0]Q
  );

  always @ (a,b,c,d)
  begin

    Q[0] = | d | b ;
    Q[1] = | d | c ;

  end
endmodule


module DIG_Neg #(
    parameter Bits = 1
)
(
      input signed [(Bits-1):0] in,
      output signed [(Bits-1):0] out
);
    assign out = -in;
endmodule


module DIG_Sub #(
    parameter Bits = 2
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits-1):0] s,
    output c_o
);
    wire [Bits:0] temp;

    assign temp = a - b - c_i;
    assign s = temp[(Bits-1):0];
    assign c_o = temp[Bits];
endmodule


module Mux_16x1_NBits #(
    parameter Bits = 2
)
(
    input [3:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    input [(Bits - 1):0] in_8,
    input [(Bits - 1):0] in_9,
    input [(Bits - 1):0] in_10,
    input [(Bits - 1):0] in_11,
    input [(Bits - 1):0] in_12,
    input [(Bits - 1):0] in_13,
    input [(Bits - 1):0] in_14,
    input [(Bits - 1):0] in_15,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_16x1
(
    input [3:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    input in_8,
    input in_9,
    input in_10,
    input in_11,
    input in_12,
    input in_13,
    input in_14,
    input in_15,
    output reg out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule

module or_signal
  (
    input [15:0]D,
    output O
  );

 

  assign O = ~|D;


endmodule

module Alu (
  input [15:0] A,
  input [15:0] B,
  input carryIn,
  input [5:0] AluOp,
  output [15:0] Out,
  output Neg,
  output Zero,
  output CarryOut
);
  wire [3:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire [15:0] s7;
  wire [15:0] s8;
  wire [15:0] s9;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [15:0] s12;
  wire [15:0] Out_temp;
  wire [3:0] s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire [4:0] sel;
  wire s19;
  wire s20;
  assign s3 = (A & B);
  assign s4 = (A | B);
  assign s5 = (A ^ B);
  assign s19 = (AluOp[5] & carryIn);
  assign s6 = ~ A;
  DIG_Neg #(
    .Bits(16)
  )
  DIG_Neg_i0 (
    .in( A ),
    .out( s7 )
  );
  assign s12[3:0] = A[7:4];
  assign s12[7:4] = A[3:0];
  assign s12[11:8] = A[15:12];
  assign s12[15:12] = A[11:8];
  assign s11[7:0] = A[15:8];
  assign s11[15:8] = A[7:0];
  assign sel = AluOp[4:0];
  assign s18 = A[0];
  assign s20 = A[15];
  assign s17 = A[0];
  assign s16 = A[15];
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i1 (
    .a( A ),
    .b( B ),
    .c_i( s19 ),
    .s( s1 ),
    .c_o( s14 )
  );
  DIG_Sub #(
    .Bits(16)
  )
  DIG_Sub_i2 (
    .a( A ),
    .b( B ),
    .c_i( s19 ),
    .s( s2 ),
    .c_o( s15 )
  );
  assign s10[13:0] = A[14:1];
  assign s10[14] = s20;
  assign s10[15] = s20;
  assign s9[14:0] = A[15:1];
  assign s9[15] = s19;
  assign s8[0] = s19;
  assign s8[15:1] = A[14:0];
  assign s13 = sel[3:0];
  assign s0 = sel[3:0];
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i3 (
    .sel( s0 ),
    .in_0( B ),
    .in_1( s1 ),
    .in_2( s2 ),
    .in_3( s3 ),
    .in_4( s4 ),
    .in_5( s5 ),
    .in_6( s6 ),
    .in_7( s7 ),
    .in_8( s8 ),
    .in_9( s9 ),
    .in_10( s10 ),
    .in_11( s11 ),
    .in_12( s12 ),
    .in_13( A ),
    .in_14( 16'b0 ),
    .in_15( 16'b0 ),
    .out( Out_temp )
  );
  Mux_16x1 Mux_16x1_i4 (
    .sel( s13 ),
    .in_0( 1'b0 ),
    .in_1( s14 ),
    .in_2( s15 ),
    .in_3( 1'b0 ),
    .in_4( 1'b0 ),
    .in_5( 1'b0 ),
    .in_6( 1'b0 ),
    .in_7( 1'b0 ),
    .in_8( s16 ),
    .in_9( s17 ),
    .in_10( s18 ),
    .in_11( 1'b0 ),
    .in_12( 1'b0 ),
    .in_13( 1'b0 ),
    .in_14( 1'b0 ),
    .in_15( 1'b0 ),
    .out( CarryOut )
  );
  // or_signal
  or_signal or_signal_i5 (
    .D( Out_temp ),
    .O( Zero )
  );
  assign Neg = Out_temp[15];
  assign Out = Out_temp;
endmodule

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module CompSigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = $signed(a) > $signed(b);
    assign \= = $signed(a) == $signed(b);
    assign \< = $signed(a) < $signed(b);
endmodule


module tt_um_remedy_cpu (
  input [7:0] ui_in,
  input clk,
  input [7:0] uio_in,
  input ena,
  input rst_n,
  output [7:0] uo_out,
  output [7:0] uio_out,
  output [7:0] uio_oe
);
  wire muxA;
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [2:0] muxB;
  wire [15:0] ImmReg;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire [15:0] inst_reg;
  wire [3:0] s7;
  wire [3:0] s8;
  wire [7:0] OPcode;
  wire [1:0] s9;
  wire [15:0] s10;
  wire [15:0] mem_out;
  wire [15:0] iow_Din;
  wire [15:0] s11;
  wire [15:0] s12;
  wire [1:0] s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire [2:0] br;
  wire [7:0] s18;
  wire imm;
  wire [1:0] iem;
  wire s19;
  wire [15:0] inputReg;
  wire [7:0] inputFromOutside;
  wire [6:0] s20;
  wire [6:0] s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire [5:0] aluOp;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire intr;
  wire \execute-pulse ;
  wire s36;
  wire Reti;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire [7:0] s41;
  wire [7:0] uo_out_temp;
  wire s42;
  wire sf;
  wire s43;
  wire s44;
  wire pc_en;
  wire s45;
  wire s46;
  wire [15:0] programAddr;
  wire s47;
  wire s48;
  wire stPC;
  wire [15:0] outR;
  wire spi_st;
  wire spi_ld;
  wire [15:0] spi_addr;
  wire [15:0] spi_data_out;
  wire spi_miso;
  wire [15:0] spi_data;
  wire spi_cs;
  wire spi_clock_ram;
  wire spi_busy_ram;
  wire spi_mosi_ram;
  wire s49;
  wire WE;
  wire ld;
  wire data_done;
  wire s50;
  wire s51;
  wire s52;
  wire Fetch_done;
  wire abs;
  wire s53;
  wire s54;
  wire s55;
  wire s56;
  wire \sda-in ;
  wire \scl-in ;
  wire dbg_data_in;
  wire spics_ram;
  wire spics_flash;
  wire sda_o;
  wire scl_o;
  wire dbg_data_out;
  wire sda_oe;
  wire scl_oe;
  wire dbg_data_oe;
  wire [3:0] s57;
  wire [2:0] s58;
  wire [15:0] intr_reg;
  wire InterLock;
  wire s59;
  wire s60;
  wire i2c_inter;
  wire [7:0] s61;
  wire [15:0] rngdat0;
  wire [15:0] timerdat1;
  wire [8:0] s62;
  wire [15:0] timerdat2;
  wire [2:0] s63;
  wire [15:0] i2cDat;
  wire [4:0] s64;
  wire s65;
  wire [3:0] s66;
  wire st;
  wire flash_req;
  wire Break;
  wire spi_target;
  wire s67;
  wire s68;
  wire s69;
  wire s70;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire [2:0] flag_out;
  wire dbg_clk;
  wire [15:0] reg_rdata;
  wire s75;
  wire [3:0] s76;
  wire [15:0] s77;
  wire s78;
  wire s79;
  wire s80;
  wire s81;
  wire dbg_en;
  wire halt_req;
  wire run_req;
  wire step_req;
  wire s82;
  wire s83;
  wire fetch_request_pulse;
  wire dbg_halted;
  wire ststic_break_en;
  wire [15:0] bp0;
  wire bp_en;
  Mux_2x1 Mux_2x1_i0 (
    .sel( ena ),
    .in_0( 1'b1 ),
    .in_1( clk ),
    .out( s19 )
  );
  assign inputFromOutside[6:0] = ui_in[6:0];
  assign inputFromOutside[7] = 1'b0;
  assign spi_miso = uio_in[0];
  assign s53 = uio_in[1];
  assign s54 = uio_in[2];
  assign s55 = uio_in[3];
  assign s56 = uio_in[4];
  assign \sda-in  = uio_in[5];
  assign \scl-in  = uio_in[6];
  assign dbg_data_in = uio_in[7];
  assign dbg_clk = ui_in[7];
  assign inputReg[0] = inputFromOutside[0];
  assign inputReg[1] = inputFromOutside[1];
  assign inputReg[2] = inputFromOutside[2];
  assign inputReg[3] = inputFromOutside[3];
  assign inputReg[4] = inputFromOutside[4];
  assign inputReg[5] = inputFromOutside[5];
  assign inputReg[6] = inputFromOutside[6];
  assign inputReg[7] = inputFromOutside[7];
  assign inputReg[15:8] = 8'b0;
  ImReg ImReg_i1 (
    .en( imm ),
    .iem( iem ),
    .C( s19 ),
    .inst( inst_reg ),
    .imm( ImmReg )
  );
  // NegR
  register_1bit register_1bit_i2 (
    .D( s42 ),
    .C( s19 ),
    .en( sf ),
    .rst( rst_n ),
    .Q( s16 )
  );
  // ZeroR
  register_1bit register_1bit_i3 (
    .D( s43 ),
    .C( s19 ),
    .en( sf ),
    .rst( rst_n ),
    .Q( s15 )
  );
  // CarryR
  register_1bit register_1bit_i4 (
    .D( s44 ),
    .C( s19 ),
    .en( sf ),
    .rst( rst_n ),
    .Q( s14 )
  );
  // outputReg
  register_8bit register_8bit_i5 (
    .D( s41 ),
    .C( s19 ),
    .en( s40 ),
    .rst( rst_n ),
    .Q( uo_out_temp )
  );
  // programCounter
  programCounter programCounter_i6 (
    .AluIn( s10 ),
    .clk( s19 ),
    .rst_n( rst_n ),
    .pc_en( pc_en ),
    .absJmp( s45 ),
    .intr( s36 ),
    .reti( s37 ),
    .relJmp( s46 ),
    .PC( programAddr )
  );
  // spi_memory_interface
  spi_memory_interface spi_memory_interface_i7 (
    .clk( s19 ),
    .spi_rst_n( rst_n ),
    .st( spi_st ),
    .ld( spi_ld ),
    .addr( spi_addr ),
    .data_in( spi_data_out ),
    .spi_miso( spi_miso ),
    .data_out( spi_data ),
    .spi_cs( spi_cs ),
    .spi_clk( spi_clock_ram ),
    .busy( spi_busy_ram ),
    .spi_mosi( spi_mosi_ram )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i8 (
    .D( mem_out ),
    .C( s19 ),
    .en( Fetch_done ),
    .Q( inst_reg )
  );
  // interrupt_controller_small
  interrupt_controller_small interrupt_controller_small_i9 (
    .dOut( s57 ),
    .Addr( s10 ),
    .ioW( s39 ),
    .C( s19 ),
    .rst_n( rst_n ),
    .irq_in( s58 ),
    .imm( imm ),
    .reti( Reti ),
    .pc_en( pc_en ),
    .CPUInterruptEnableAddr( 16'b1101 ),
    .inputInterruptAddr( 16'b1110 ),
    .interruptRegAddr( 16'b1111 ),
    .InterruptOut( intr_reg ),
    .intr( intr ),
    .irq_lock( InterLock )
  );
  // lfsr_RandomNumberGen
  lfsr_RandomNumberGen lfsr_RandomNumberGen_i10 (
    .adrrIn( s10 ),
    .dataIn( s61 ),
    .ioW( s39 ),
    .clk( s19 ),
    .SeedAdr( 16'b1011 ),
    .RngAdr( 16'b1100 ),
    .Out( rngdat0 )
  );
  // timer
  timer timer_i11 (
    .dOut( s1 ),
    .Addr( s10 ),
    .ioW( s39 ),
    .C( s19 ),
    .InterLock( InterLock ),
    .timerConfigAddr( 16'b10 ),
    .timerTargetAddr( 16'b11 ),
    .timerResetAddr( 16'b100 ),
    .timerReadAddr( 16'b101 ),
    .timerSyncStartAddr( 16'b1010 ),
    .rst_n( rst_n ),
    .TimerOut( timerdat1 ),
    .timer_interrupt( s59 )
  );
  // timer_tiny
  timer_tiny timer_tiny_i12 (
    .dOut( s62 ),
    .Addr( s10 ),
    .ioW( s39 ),
    .C( s19 ),
    .InterLock( InterLock ),
    .timerConfigAddr( 16'b110 ),
    .timerTargetAddr( 16'b111 ),
    .timerResetAddr( 16'b1000 ),
    .timerReadAddr( 16'b1001 ),
    .timerSyncStartAddr( 16'b1010 ),
    .rst_n( rst_n ),
    .TimerOut( timerdat2 ),
    .timer_interrupt( s60 )
  );
  // RegisterBlock
  RegisterBlock RegisterBlock_i13 (
    .DataIn( s12 ),
    .WE( WE ),
    .clk( s19 ),
    .src( s7 ),
    .Dest( s8 ),
    .RDest( s0 ),
    .Rsrc( s1 )
  );
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i14 (
    .sel( s63 ),
    .in_0( inputReg ),
    .in_1( outR ),
    .in_2( timerdat1 ),
    .in_3( timerdat2 ),
    .in_4( rngdat0 ),
    .in_5( intr_reg ),
    .in_6( i2cDat ),
    .in_7( i2cDat ),
    .out( iow_Din )
  );
  // i2c_master_ctrl
  i2c_master_ctrl i2c_master_ctrl_i15 (
    .clk( s19 ),
    .rst_n( rst_n ),
    .wr_en( s65 ),
    .reg_addr( s66 ),
    .cpu_din( s1 ),
    .sda_in( \sda-in  ),
    .scl_in( \scl-in  ),
    .cpu_dout( i2cDat ),
    .sda_out( sda_o ),
    .scl_out( scl_o ),
    .sda_oe( sda_oe ),
    .scl_oe( scl_oe ),
    .interrupt( i2c_inter )
  );
  // debug_serial_frontend_tiny
  debug_serial_frontend_tiny debug_serial_frontend_tiny_i16 (
    .cpu_clk( s19 ),
    .rst_n( rst_n ),
    .dbg_clk( dbg_clk ),
    .dbg_data_in( dbg_data_in ),
    .reg_rdata( reg_rdata ),
    .dbg_data_out( dbg_data_out ),
    .dbg_data_oe( dbg_data_oe ),
    .reg_wr( s75 ),
    .reg_addr( s76 ),
    .reg_wdata( s77 )
  );
  // cpu_cycle_controller_tiny
  cpu_cycle_controller_tiny cpu_cycle_controller_tiny_i17 (
    .clk( s19 ),
    .rst_n( rst_n ),
    .fetch_done( Fetch_done ),
    .data_done( data_done ),
    .ld( ld ),
    .st( st ),
    .flash_ld( flash_req ),
    .dbg_enable( dbg_en ),
    .dbg_halt_req( halt_req ),
    .dbg_run_req( run_req ),
    .dbg_step_req( step_req ),
    .dbg_break_hit( s82 ),
    .dbg_break_after_exec( s83 ),
    .fetch_req( fetch_request_pulse ),
    .execute_now_pulse( \execute-pulse  ),
    .dbg_halted( dbg_halted )
  );
  // memory_wait_controller_tiny
  memory_wait_controller_tiny memory_wait_controller_tiny_i18 (
    .clk( s19 ),
    .rst_n( rst_n ),
    .fetch_req( fetch_request_pulse ),
    .ld_req( s78 ),
    .st_req( s79 ),
    .flash_req( s81 ),
    .fetch_addr( programAddr ),
    .data_addr( s10 ),
    .store_data( s1 ),
    .spi_data_out( spi_data ),
    .spi_busy( spi_busy_ram ),
    .mem_rdata( mem_out ),
    .fetch_done( Fetch_done ),
    .data_done( data_done ),
    .mem_stall( s80 ),
    .spi_st( spi_st ),
    .spi_ld( spi_ld ),
    .spi_addr( spi_addr ),
    .spi_data_in( spi_data_out ),
    .spi_target( spi_target )
  );
  // debug_core_tiny
  debug_core_tiny debug_core_tiny_i19 (
    .clk( s19 ),
    .rst_n( rst_n ),
    .reg_wr( s75 ),
    .reg_addr( s76 ),
    .reg_wdata( s77 ),
    .cpu_dbg_halted( dbg_halted ),
    .cpu_flags( flag_out ),
    .cpu_pc( programAddr ),
    .cpu_ir( inst_reg ),
    .reg_rdata( reg_rdata ),
    .dbg_enable( dbg_en ),
    .dbg_halt_req( halt_req ),
    .dbg_run_req( run_req ),
    .dbg_step_req( step_req ),
    .static_break_enable( ststic_break_en ),
    .bp0( bp0 ),
    .bp_enable( bp_en )
  );
  // breakpoint_logic_tiny
  breakpoint_logic_tiny breakpoint_logic_tiny_i20 (
    .clk( s19 ),
    .rst_n( rst_n ),
    .dbg_enable( dbg_en ),
    .dbg_halted( dbg_halted ),
    .dbg_run_req( run_req ),
    .dbg_step_req( step_req ),
    .execute_now_pulse( \execute-pulse  ),
    .pc( programAddr ),
    .bp0( bp0 ),
    .bp_enable( bp_en ),
    .instr_is_brk( Break ),
    .static_break_enable( ststic_break_en ),
    .dbg_break_hit( s82 ),
    .dbg_break_after_exec( s83 )
  );
  assign s36 = (intr & \execute-pulse );
  assign outR[7:0] = uo_out_temp;
  assign outR[15:8] = 8'b0;
  assign uio_oe[0] = 1'b0;
  assign uio_oe[1] = 1'b1;
  assign uio_oe[2] = 1'b1;
  assign uio_oe[3] = 1'b1;
  assign uio_oe[4] = 1'b1;
  assign uio_oe[5] = sda_oe;
  assign uio_oe[6] = scl_oe;
  assign uio_oe[7] = dbg_data_oe;
  assign s58[0] = s59;
  assign s58[1] = s60;
  assign s58[2] = i2c_inter;
  Mux_2x1 Mux_2x1_i21 (
    .sel( spi_target ),
    .in_0( 1'b1 ),
    .in_1( spi_cs ),
    .out( spics_ram )
  );
  assign s67 = ~ spi_target;
  assign flag_out[0] = s16;
  assign flag_out[1] = s15;
  assign flag_out[2] = s14;
  assign pc_en = (~ s80 & \execute-pulse );
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i22 (
    .a( programAddr ),
    .b( 16'b1 ),
    .c_i( 1'b0 ),
    .s( s11 )
  );
  assign s7 = inst_reg[3:0];
  assign s8 = inst_reg[7:4];
  assign OPcode = inst_reg[15:8];
  assign s41 = s1[7:0];
  assign s18 = inst_reg[7:0];
  assign s62 = s1[8:0];
  assign s61 = s1[7:0];
  assign s57 = s1[3:0];
  singExtend singExtend_i23 (
    .inst( s18 ),
    .\4S ( s3 ),
    .\8SD ( s4 ),
    .\4D ( s5 )
  );
  Mux_2x1 Mux_2x1_i24 (
    .sel( s67 ),
    .in_0( 1'b1 ),
    .in_1( spi_cs ),
    .out( spics_flash )
  );
  assign s20 = OPcode[6:0];
  assign imm = OPcode[7];
  Mux_2x1_NBits #(
    .Bits(7)
  )
  Mux_2x1_NBits_i25 (
    .sel( imm ),
    .in_0( s20 ),
    .in_1( 7'b0 ),
    .out( s21 )
  );
  assign uio_out[0] = 1'b0;
  assign uio_out[1] = spics_ram;
  assign uio_out[2] = spics_flash;
  assign uio_out[3] = spi_mosi_ram;
  assign uio_out[4] = spi_clock_ram;
  assign uio_out[5] = sda_o;
  assign uio_out[6] = scl_o;
  assign uio_out[7] = dbg_data_out;
  // opcode_microcode_rom
  opcode_microcode_rom opcode_microcode_rom_i26 (
    .opcode( s21 ),
    .muxb0( s24 ),
    .muxb1( s23 ),
    .muxb2( s22 ),
    .aluop0( s30 ),
    .aluop1( s29 ),
    .aluop2( s28 ),
    .aluop3( s27 ),
    .aluop4( s26 ),
    .aluop5( s25 ),
    .WE( s49 ),
    .sf( s50 ),
    .iem0( s35 ),
    .iem1( s34 ),
    .br0( s33 ),
    .br1( s32 ),
    .br2( s31 ),
    .muxA( muxA ),
    .ld( ld ),
    .st( st ),
    .abs( abs ),
    .ioW( s51 ),
    .ioR( s52 ),
    .stPC( stPC ),
    .Reti( Reti ),
    .flash_req( flash_req ),
    .Brk( Break )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i27 (
    .sel( muxA ),
    .in_0( s0 ),
    .in_1( s1 ),
    .out( s2 )
  );
  assign muxB[0] = s22;
  assign muxB[1] = s23;
  assign muxB[2] = s24;
  assign aluOp[0] = s25;
  assign aluOp[1] = s26;
  assign aluOp[2] = s27;
  assign aluOp[3] = s28;
  assign aluOp[4] = s29;
  assign aluOp[5] = s30;
  assign br[0] = s31;
  assign br[1] = s32;
  assign br[2] = s33;
  assign iem[0] = s34;
  assign iem[1] = s35;
  assign s37 = (\execute-pulse  & Reti);
  assign WE = (((~ flash_req | ~ ld) & \execute-pulse  & s49) | (s49 & data_done & (flash_req | ld)));
  assign sf = (s50 & \execute-pulse );
  assign s39 = (s51 & \execute-pulse );
  assign s48 = (s52 & \execute-pulse );
  assign s45 = (abs & \execute-pulse );
  assign s47 = (flash_req | ld);
  assign s78 = (ld & \execute-pulse );
  assign s79 = (\execute-pulse  & st);
  assign s81 = (\execute-pulse  & flash_req);
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i28 (
    .sel( muxB ),
    .in_0( s1 ),
    .in_1( 16'b0 ),
    .in_2( ImmReg ),
    .in_3( 16'b0 ),
    .in_4( 16'b0 ),
    .in_5( s3 ),
    .in_6( s4 ),
    .in_7( s5 ),
    .out( s6 )
  );
  // muxEncoder
  muxEncoder muxEncoder_i29 (
    .a( 1'b0 ),
    .b( s47 ),
    .c( s48 ),
    .d( stPC ),
    .Q( s9 )
  );
  assign s13 = br[1:0];
  Mux_4x1 Mux_4x1_i30 (
    .sel( s13 ),
    .in_0( 1'b0 ),
    .in_1( s14 ),
    .in_2( s15 ),
    .in_3( s16 ),
    .out( s17 )
  );
  Alu Alu_i31 (
    .A( s2 ),
    .B( s6 ),
    .carryIn( s14 ),
    .AluOp( aluOp ),
    .Out( s10 ),
    .Neg( s42 ),
    .Zero( s43 ),
    .CarryOut( s44 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i32 (
    .sel( s9 ),
    .in_0( s10 ),
    .in_1( mem_out ),
    .in_2( iow_Din ),
    .in_3( s11 ),
    .out( s12 )
  );
  CompSigned #(
    .Bits(16)
  )
  CompSigned_i33 (
    .a( s10 ),
    .b( 16'b1 ),
    .\= ( s38 )
  );
  assign s46 = ((s17 ^ br[2]) & \execute-pulse );
  assign s65 = (s10[4] & s39);
  assign s64 = s10[4:0];
  assign s66 = s10[3:0];
  assign s40 = (s38 & s39);
  assign s68 = s64[0];
  assign s69 = s64[1];
  assign s70 = s64[2];
  assign s71 = s64[3];
  assign s72 = s64[4];
  assign s73 = ~ s70;
  assign s74 = ~ s69;
  assign s63[0] = ((~ s72 & s73 & s74 & s68) | (s71 & s74 & s68) | (s71 & s73 & s74) | (s70 & s69));
  assign s63[1] = (s72 | (~ s71 & s69) | (~ s71 & s70) | (s71 & s73 & s74));
  assign s63[2] = (s72 | (s71 & s69 & s68) | (s71 & s70));
  assign uo_out = uo_out_temp;
endmodule
